name: Build and Release Debian Packages

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [ trixie ]
        #distro: [trixie, forky]
        arch: [amd64, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y podman qemu-user-static

      - name: Extract version
        id: version
        run: |
          echo "mailscanner=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Build package
        run: |
          ./build-and-extract.sh \
            "${{ steps.version.outputs.mailscanner }}" \
            "${{ matrix.distro }}" \
            "${{ matrix.arch }}" \
            dist

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: debs-${{ matrix.distro }}-${{ matrix.arch }}
          path: dist/*.deb

      - name: Upload SHA256SUM
        uses: actions/upload-artifact@v4
        with:
          name: debs-${{ matrix.distro }}-${{ matrix.arch }}-sha256
          path: dist/*.deb.sha256

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Import GPG key
        run: echo "${{ secrets.DEB_GPG_PRIVATE_KEY }}" | base64 -d | gpg --batch --import

      - name: Create Combined SHA256SUMS
        run: |
          cd artifacts
          find . -name "*.deb" -exec sha256sum {} \; > SHA256SUMS

      - name: Sign SHA256SUMS
        working-directory: artifacts
        run: |
          gpg --batch --yes \
            --pinentry-mode loopback \
            --passphrase "${{ secrets.DEB_GPG_PASSPHRASE }}" \
            --armor --detach-sign SHA256SUMS

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/**/*.deb
            artifacts/**/*.deb.sha256
            artifacts/SHA256SUMS
            artifacts/SHA256SUMS.asc
          token: ${{ secrets.RELEASE_TOKEN }}
          overwrite_files: true

      - name: Trigger repo update
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DEBS_REPO_TRIGGER }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/SpamTagger/debs/actions/workflows/publish.yml/dispatches \
                -d '{"ref":"main","inputs":{"trigger-repo":"st-mailscanner","version":"${{ steps.version.outputs.mailscanner }}"}}'
